
steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Build
    run: |
      make lovefile

  - name: Upload
    uses: actions/upload-artifact@v2
    with:
      name: funkin-rewritten-lovefile
      path: build/lovefile
